### ISSUE TITLE
Tested under Linux?

### ISSUE THREAD

**Issue by svenkuegler** [spocke/php-debugger#12]
Hi, 

I use Brackets with your Plugin under Ubuntu 14.04. The communication between xdebug and your Plugin seems to work. But ive never get some Information in the Info Window at the bottom. 

Only the 5 Buttons are enabled and seems to send Commands to xdebug.

Is the Plugin tested under Linux? Can you reproduce this?

Greetings from Berlin
Sven

**Comment by spocke** [comment]
Haven't tested it on Linux or Mac just on Windows. Could be path problems or xdebug version problems.

**Comment by svenkuegler** [comment]
**Here is the Console Output:**

Exception in 'data' listener on 
NodeDomain
 TypeError: Cannot call method 'indexOf' of undefined TypeError: Cannot call method 'indexOf' of undefined
    at Object.toEditorPath (file:///home/sven/.config/Brackets/extensions/user/php-debugger/lib/util.js:68:17)
    at Object.exports.open (file:///home/sven/.config/Brackets/extensions/user/php-debugger/lib/editor.js:256:19)
    at Object.exports.setActiveLine (file:///home/sven/.config/Brackets/extensions/user/php-debugger/lib/editor.js:299:18)
    at moveToBreakLine (file:///home/sven/.config/Brackets/extensions/user/php-debugger/lib/xdebug.js:199:11)
    at file:///home/sven/.config/Brackets/extensions/user/php-debugger/lib/xdebug.js:238:5
    at NodeDomain.trigger (/utils/EventDispatcher.js:222:40)
    at Object.triggerWithArray (/utils/EventDispatcher.js:260:28)
    at NodeDomain.eval (/utils/NodeDomain.js:143:41)
    at NodeConnection.trigger (/utils/EventDispatcher.js:222:40)
    at Object.triggerWithArray (/utils/EventDispatcher.js:260:28)

**Comment by svenkuegler** [comment]
I have tested a little bit .... The creation of `new URL()` at [Line 64 in lib/util.js](https://github.com/spocke/php-debugger/blob/master/lib/util.js#L64) produce the Error! On Unix based Systems the URL Object is empty and has no poperty **pathname**.

Temporarily I have replaced ...

``` javascript
var fileUri = new URL(fullPath);
fullPath = fileUri.pathname;
```

with:

``` javascript
fullPath = fullPath.replace("file:///", "/");
```

Works also fine under Windows.

Greetings Sven

**Comment by spocke** [comment]
Thanks for looking into this. Added it to the repo.
